export const stateMapping = {
  "Andhra Pradesh": "Kulcharam Atishaykshetra",
  Assam: "Suryapahad Atishaykshetra",
  Bihar: [
    "Arrah Atishaykshetra",
    "Basokund (Vaishali) Kalyanakksetra",
    "Champapur Siddhakshetra",
    "Gunawaji Siddhakshetra",
    "Kamaldahji Siddhakshetra",
    "Kundalpur Kalyanakksetra",
    "Kundalpur-Nandyavart Mahal Kalyanakksetra",
    "Mandargir Siddhakshetra",
    "Pawapuri Siddhakshetra",
    "Rajgirji Siddhakshetra",
  ],
  Gujarat: [
    "Vaishali Atishaykshetra",
    "Bhiloda Atishaykshetra",
    "Chetanyadham Sadhnatirth",
    "Derol-Vaghela Atishaykshetra",
    "Ghogha Atishaykshetra",
    "Girnarji Siddhakshetra",
    "Mahua Atishaykshetra",
    "Pawagarh Siddhakshetra",
    "Shatrunjayaji Siddhakshetra",
    "Tarangaji Siddhakshetra",
    "Umata Atishaykshetra",
  ],
  Haryana: [
    "Hansi Atishaykshetra",
    "Kasangaon Atishaykshetra",
    "Ranila Atishaykshetra",
    "Rohtak Atishaykshetra",
    "Shikohpur Atishaykshetra",
  ],
  Jharkhand: ["Kolhua Pahad Siddhakshetra", "Sammedshikharji Siddhakshetra"],
  Karnataka: [
    "Bijapur Atishaykshetra",
    "Dharmasthal Kalakshetra",
    "Harsur Atishaykshetra",
    "Humcha Atishaykshetra",
    "Hunse Hadgali Atishaykshetra",
    "Jwalamalini Atishaykshetra",
    "Kamthan Atishaykshetra",
    "Kanakgiri (Maleyur) Siddhakshetra",
    "Karkal Atishaykshetra",
    "Kothali Otherkshetra",
    "Malkhed Atishaykshetra",
    "Mudbidri Atishaykshetra",
    "Shankhabasdi Kalakshetra",
    "Shrawanbelgola Atishaykshetra",
    "Stavanidhi (Tavandi) Atishaykshetra",
    "Venur Kalakshetra",
  ],
  "Madhya Pradesh": [
    "Aahuji Atishaykshetra",
    "Aharji Siddhakshetra",
    "Ajaygarh Atishaykshetra",
    "Amarkantak Atishaykshetra",
    "Badi Atishaykshetra",
    "Badoh Kalakshetra",
    "Bahi Parshvanath Atishaykshetra",
    "Bahoriband Atishaykshetra",
    "Bajranggarh Atishaykshetra",
    "Bandhaji Atishaykshetra",
    "Banediyaji Atishaykshetra",
    "Baransoji Atishaykshetra",
    "Barela Atishaykshetra",
    "Barhi Atishaykshetra",
    "Bawangaja Siddhakshetra",
    "Bhojpur Atishaykshetra",
    "Bhourasa Atishaykshetra",
    "Bijori Atishaykshetra",
    "Binaji (Barha) Atishaykshetra",
    "Chanderi Atishaykshetra",
    "Chota Mahaveerji Atishaykshetra",
    "Drongiri Siddhakshetra",
    "Eshurwara Atishaykshetra",
    "Falhodi Badagaon Siddhakshetra",
    "Gandharvapuri Puratatvakshetra",
    "Golakot Atishaykshetra",
    "Gommatgiri Atishaykshetra",
    "Gopachal Parwat Siddhakshetra",
    "Gudar Atishaykshetra",
    "Gwalior-Swarna Mandir Darshankshetra",
    "Gyaraspur Atishaykshetra",
    "Jamner Atishaykshetra",
    "Jaysinghpura-Ujjain Atishaykshetra",
    "Kaithuli Atishaykshetra",
    "Khajuraho Atishaykshetra",
    "Khandargiri Atishaykshetra",
    "Khaniyadhana Darshankshetra",
    "Kundalgiri (Koniji) Atishaykshetra",
    "Kundalpur (Damoh) Siddhakshetra",
    "Lakhnadaun Atishaykshetra",
    "Shri Mahavir-Tapobhumi-Ujjain Atishaykshetra",
    "Maksi-Parshvanath Atishaykshetra",
    "Mangalgiri (Sagar) Atishaykshetra",
    "Manhardev Atishaykshetra",
    "Mantunggiri Atishaykshetra",
    "Muktagiri Siddhakshetra",
    "Nainagiri Siddhakshetra",
    "Nemawar (Siddhodaya) Siddhakshetra",
    "Nemigiri Banda Atishaykshetra",
    "Nisaiji Otherkshetra",
    "Nisaiji Sukha Atishaykshetra",
    "Nohta Atishaykshetra",
    "Pacharai Atishaykshetra",
    "Pajnari Atishaykshetra",
    "Panagar Atishaykshetra",
    "Panigaon Kalakshetra",
    "Paporaji Atishaykshetra",
    "Parshvagiri (Badwani) Atishaykshetra",
    "Pateria (Gadakota) Atishaykshetra",
    "Patnaganj (Raheli) Atishaykshetra",
    "Paawai (Pawagadh) Atishaykshetra",
    "Pidruva Atishaykshetra",
    "Pisanhari-Madiyaji Atishaykshetra",
    "Pushpagiri Atishaykshetra",
    "Pushpavati Bilhari Atishaykshetra",
    "Semarkhedi (Nisaiji) Atishaykshetra",
    "Sesai Atishaykshetra",
    "Shreyansgiri Atishaykshetra",
    "Siddhvarkut Siddhakshetra",
    "Sihoniyaji Atishaykshetra",
    "Sironj Atishaykshetra",
    "Sonagiriji Siddhakshetra",
    "Talanpur Atishaykshetra",
    "Tejgarh Atishaykshetra",
    "Thubonji Atishaykshetra",
    "Tigodaji Atishaykshetra",
    "Un (Pawagiri) Siddhakshetra",
    "Urwaha Atishaykshetra",
  ],
  Maharashtra: [
    "Aasegaon Atishaykshetra",
    "Aashta (Kasar) Atishaykshetra",
    "Anjangiri Atishaykshetra",
    "Antariksha Parshvanath Atishaykshetra",
    "Bhatkuli Jain Atishaykshetra",
    "Dahigaon Atishaykshetra",
    "Dharangaon Atishaykshetra",
    "Ellora (Verul) Atishaykshetra",
    "Gajpantha Siddhakshetra",
    "Jatwada Atishaykshetra",
    "Kachner Atishaykshetra",
    "Karanja (Lad) Atishaykshetra",
    "Kaudanyapur Atishaykshetra",
    "Kesapuri-Bir Atishaykshetra",
    "Kumbhoj Bahubali Atishaykshetra",
    "Kundal Siddhakshetra",
    "Kunthalgiri Siddhakshetra",
    "Kunthugiri Atishaykshetra",
    "Mandal Atishaykshetra",
    "Mangitungi Siddhakshetra",
    "Mangitungi Rishabhgiri Atishaykshetra",
    "Mulawa Atishaykshetra",
    "Naichakur Atishaykshetra",
    "Namokar tirth Atishaykshetra",
    "Nandishwar-Panchaleshwar Atishaykshetra",
    "Nawagarh Atishaykshetra",
    "Nemgiri Jintur Atishaykshetra",
    "Paithan Atishaykshetra",
    "Podanpur (Borivalli) Atishaykshetra",
    "Ramtek Atishaykshetra",
    "Sawargaon Atishaykshetra",
    "Shirad Atishaykshetra",
    "Ter Atishaykshetra",
    "Vijay Gopal Atishaykshetra",
  ],
  Orissa: "Khandgiri-Udaygiri Siddhakshetra",
  Rajasthan: [
    "Adinda Atishaykshetra",
    "Andeshwar Parshvanath Atishaykshetra",
    "Anwa Atishaykshetra",
    "Arthuna Nasiyaji Atishaykshetra",
    "Bijoliya parshvanath Atishaykshetra",
    "Chamatkarji Atishaykshetra",
    "Chandkhedi Atishaykshetra",
    "Chandragiri Bainad Atishaykshetra",
    "Chanwaleshwar Parshvanath Atishaykshetra",
    "Chulgiri Khaniyaji Atishaykshetra",
    "Debari Atishaykshetra",
    "Dehara-Tijara Atishaykshetra",
    "Dilwada-Mount Abu Atishaykshetra",
    "Jahajpur Atishaykshetra",
    "Jhajhirampura-Dausa Atishaykshetra",
    "Jhalarapatan Parshwagiri Atishaykshetra",
    "Keshorai Patan Atishaykshetra",
    "Khairwada Atishaykshetra",
    "Khandarji Atishaykshetra",
    "Khunadari Atishaykshetra",
    "Lohariya Atishaykshetra",
    "Mahavirji Atishaykshetra",
    "Malpura - Tonk Atishaykshetra",
    "Maujamabad Atishaykshetra",
    "Mehandwas - Tonk Atishaykshetra",
    "Nagphani Parshvanath Atishaykshetra",
    "Nareli Darshankshetra",
    "Naugama Nasiyaji Kalakshetra",
    "Padampura (Baada) Atishaykshetra",
    "Raiwasa-Seekar Atishaykshetra",
    "Rishabhdev Keshriyaji Atishaykshetra",
    "Saleda Atishaykshetra",
    "Sanghiji-Sanganer Atishaykshetra",
    "Sankhana - Tonk Atishaykshetra",
    "Sarvaad Atishaykshetra",
    "Shantinath-Bamotar Atishaykshetra",
    "Vagol-Parshvanath Atishaykshetra",
  ],
  "Tamil Nadu": [
    "Melchitamur Atishaykshetra",
    "Ponnurmalle Atishaykshetra",
    "Tirumalle Atishaykshetra",
    "Ahikhetra Parshvanath Atishaykshetra",
  ],
  Uttarakhand: "Ashtapad Kailash Badrinath Siddhakshetra",
  "Uttar Pradesh": [
    "Ayodhya Kalyanakksetra",
    "Badagaon Atishaykshetra",
    "Badagaon Trilok Tirth Atishaykshetra",
    "Bahsuma Atishaykshetra",
    "Banpur Atishaykshetra",
    "Barnava-Jila-Bagpat Atishaykshetra",
    "Bhadainiji-Varanasi Kalyanakksetra",
    "Bhelupur - Varanasi Kalyanakksetra",
    "Chandravatiji Kalyanakksetra",
    "Chandrawad (Firozabad) Atishaykshetra",
    "Devgarhji Atishaykshetra",
    "Girargiriji Atishaykshetra",
    "Hastinapur Kalyanakksetra",
    "Hastinapur-Jamboodveep Kalyanakksetra",
    "Husainpur Kalan Atishaykshetra",
    "Kahaun Kalyanakksetra",
    "Kakandi Kalyanakksetra",
    "Kampilji Kalyanakksetra",
    "Karguwanji Atishaykshetra",
    "Karitoran Atishaykshetra",
    "Kaushambi Kalyanakksetra",
    "Mahalka-Jila-Meerut Atishaykshetra",
    "Manglayatan Kalakshetra",
    "Marsalganj Atishaykshetra",
    "Mathura Chourasi Siddhakshetra",
    "Navagarh (Nandpur) Atishaykshetra",
    "Pawagirji Siddhakshetra",
    "Pawanagar Siddhakshetra",
    "Prabhasgiri (Pabhausa) Kalyanakksetra",
    "Prayag Kalyanakksetra",
    "Prayag-Rishabhadev Tapsthali Kalyanakksetra",
    "Rajmal (Firozabad) Atishaykshetra",
    "Ratanpuri Kalyanakksetra",
    "Rishabhanchal Atishaykshetra",
    "Seronji Atishaykshetra",
    "Sironji (Madawara) Atishaykshetra",
    "Shantigiri (Madanpur) Atishaykshetra",
    "Shouripur (Bateshvar) Kalyanakksetra",
    "Shravasti (Saheth-Maheth) Kalyanakksetra",
    "Sinhpuri (Sarnath) Kalyanakksetra",
    "Todi Fatehpur Atishaykshetra",
    "Trilokpur Atishaykshetra",
    "Trimurti Mandir (Etmadpur) Atishaykshetra",
    "Vahalana Atishaykshetra",
  ],
  "West Bengal": [
    "Chinsura Atishaykshetra",
    "Paakbira (Purulia) Atishaykshetra",
  ],
};
